@startuml
left to right direction
 
actor Client
actor Pompiste

 
rectangle "Pompe essence" {
    usecase "Servir de l'essence" as UC1
    usecase "Remplir la station d'essence" as UC2
}
 
Client --> UC1
Pompiste --> UC2

Pompiste --|> Client

@enduml
